CREATE TABLE IF NOT EXISTS Base (
  id INT PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE IF NOT EXISTS test (
  id INT PRIMARY KEY AUTO_INCREMENT,
  file MEDIUMBLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS accounts (
	id INT PRIMARY KEY AUTO_INCREMENT,
	account_hash BINARY(32) NOT NULL,
	subscription_id INT NOT NULL
)

CREATE TABLE IF NOT EXISTS files (
	id INT PRIMARY KEY AUTO_INCREMENT
	account_id

);
